# Generated by Django 3.1.3 on 2020-11-08 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_iscsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iscsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('IS', 'Iscsi')], max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.oauth42')),
            ],
        ),
    ]
